OUTEXE=$(ODIR)/nui
INCLUDEDIRS =. ../mfl
LIBDIRS=
LIBS=termcap
OBJS = nui.o NexusParse.o NexusReader.o
ARCHIVES = ../mfl/$(MFLLIB) /usr/local/lib/ncl/libncl.a /usr/local/lib/libedit.a
include ../Makefile.inc
-include $(DEPS)
